### ISSUE TITLE
[DOC, TRACKING TICKET] Keep the `2.0 schema.json` up to date

### ISSUE THREAD

**Issue by rustatian** [spiral/roadrunner-binary#138]
Tracking ticket. To cover:
- [x] `on_init`, server
- [x] HTTP middleware (add to the examples)
- [x] Uploads, allow option
- [x] Temporal plugin
- [x] TCP Plugin
- [x] Check KV (config key was updated)
- [x] Jobs plugin with drivers (memory, bolt, sqs, rabbitmq, beanstalk, nats)
- [x] New Relic middleware
- [x] TLS ACME
- [x] Services plugin
- [x] Websockets plugin
- [x] Broadcast plugin
- [x] Redis plugin
- [x] Metrics plugin
- [x] Status plugin
- [x] GRPC plugin
- [x] Fileserver plugin
